#spring:
#  application:
#    name: Gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: Projectinfo
#          uri: http://localhost:9091
#          predicates:
#            - Path=/project/**
#        - id: Employeeinfo
#          uri: http://localhost:9092
#          predicates:
#            - Path=/ustemps/**

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8222
#spring:
#  application:
#    name: Gateway-sr
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: Author_info
#          uri: http://localhost:8899
#          predicates:
#            - Path=/author/**
#        - id: book-service
#          uri: http://localhost:5959
#          predicates:
#            - Path=/api/**


spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST